name: Unit_test

on:
  push


jobs:
  
  build_and_test:

    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Build
        run: g++ -Wall -Werror -std=c++17 *.cpp -o project
        
      - name: Make executeable
        run: chmod +x ./battle.sh
        
      - name: generate output        
        run: ./battle.sh 
        
      - name: I/O test 
        run: diff --strip-trailing-cr output.txt good_output.txt
        
      - name: Make executeable
        run: chmod +x ./test.sh
        
      - name: generate txt file        
        run: ./test.sh 
