name: Unit_test

on:
  push


jobs:
  
  build_and_test:

    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2
        
      - name: Install dependencies
        run: sudo apt-get install -y valgrind && sudo apt-get install -y cppcheck
      - name: Gtest/Cmake instalalas
        run: sudo apt install libgtest-dev && sudo apt install cmake && cd /usr/src/gtest && sudo cmake . && sudo make  && sudo cp *.a /usr/lib && sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a && sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a
      - name: CPPCheck Static Code Analysis
        run: cppcheck --enable=all ./*.cpp 2> report.txt && cat report.txt && if grep -q "(warning)" "./report.txt"; then exit 1; fi && if grep -q "(error)" "./report.txt"; then exit 1; fi 

      - name: Upload CPPCheck report as artifact
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt
        
      - name: Build
        run: g++ -Wall -Werror -std=c++17 *.cpp -o project
        
      - name: Make executeable
        run: chmod +x ./battle.sh
        
      - name: Valgrind memory check
        run: valgrind --leak-check=full --error-exitcode=1 ./project units/thor.json units/hulk.json
        
