name: build_and_test

on:
  pull


jobs:
  
  build_and_test:

    runs-on: ubuntu-latest

   
    steps:
      
      - uses: actions/checkout@v2
      - run: g++ -Wall *.cpp
      - run: ./battle.sh 
      - run: diff output.txt good_output.txt
